global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

# Descoberta de Nós do Kubernetes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
      api_server: 'https://127.0.0.1:33917'
      tls_config:
        ca_file: /path/to/ca.crt
        insecure_skip_verify: true # Use apenas para testes em cluster local
      bearer_token_file: /path/to/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
